language: node_js
node_js:
  - node
env:
  global:
    - GH_REF: github.com/bootstrapworld/codemirror-blocks.git
    # GH_TOKEN
    - secure: SWsZE+DqgHfoajKe/dqq0ao4ENJKSnsqDbKCI1vSn0kEq9UFQ6QGLdU+0yOhHNoY9UGyWiV/jV1MT90IpYv+7kcKuxIbFBuCDnAgoq88GVAuFyKu/auC/2HSZSkZDwlZ2PmUpcXfU35itBx84tspQBHGM/LQC+zaxV09i1saV0nXMr8rvPjFsas6SfNMdg6n8Tr96Dcb7lrXhoqXXC8GQt8gusHjZY+fR3MeysPfc2dORsLIFWkG+1aIM9/65et6GGIYhhasPkHgYnOBsCOXxLG48AJ84EIa16e4U0pkxSZHpqbfGwcnLQprRHJ46jGI7khgSxsigejpIgZcnD4gAyYocM1h9WTW2YmE813gK1Vrw0jieEx8Gy/xKvnmzvgr+K6TG3LhAaZWOMTDaUNzzZhBYXcGlgHG3hhX55IznRAN2dDweT0HeSOXf48j+jBmzZ7j7ea1MBxtuTZBtMMvU1GI5WFkinJVfXzTq8tQs6Uqz1V/GAc0N9Hzb35EUukF3sggTQ3VMv/8aViIT788K42EMa0kAbBge0NKWaJDye3dhafB2sdMWoQUByf4tlDhHfM7EkcipsKhDlauLSRa0I8BTrSTNh+VxB1Oj6BDqIwNz5ACkNB67l7sSq4qyAO4Hl1+t3ekcKEVJDXiKFP/+xc5qdB3Niu2Cewq3O7D3og=
addons:
  chrome: stable
cache:
  directories:
    - yarn               # cache the yarn bundle to save time on Travis
    - /home/travis/.rvm/ # cache the RVM to save time on Travis
    - node_modules       # cache our modules
    - vendors
branches:
  only:
    - master
services:
    - xvfb
before_install:
  - export CHROME_BIN=google-chrome-stable
  - google-chrome-stable --disable-gpu http://localhost &
  - rvm install 2.2.7
  - gem install public_suffix -v 2.0.5
  - gem install ruby_dep -v 1.3.1
  - gem install ffi -v 1.12.2
  - gem install jekyll -v 3.6.2
install: npm install
notifications:
  email:
    - schanzer@bootstrapworld.org
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/6184180c077043a1109a'
    on_success: change
    on_failure: always
    on_start: never
after_success:
- |
    if [ "$TRAVIS_PULL_REQUEST" = false ]; then
      ./deploy-ghpages.sh
    fi
